name: flutter_advanced_boilerplate
description: A new advanced flutter boilerplate project uses BLoC.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+6

environment:
  sdk: ">=3.0.6 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependency_overrides: null
# connectivity_plus: 4.0.1
# http: 1.1.0
# intl: 0.18.1
dependencies:
  animations: ^2.0.11
  auto_route: ^7.8.4
  auto_size_text: 3.0.0
  cached_network_image: ^3.4.1
  custom_sliding_segmented_control: ^1.8.1
  data_channel: 2.0.0+1
  device_preview: ^1.2.0
  dio: ^5.4.0
  dynamic_color: ^1.6.9
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_displaymode: 0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: 2.4.1
  fresh_dio: ^0.4.1
  get_it: ^7.6.7
  http: ^1.2.0
  hydrated_bloc: ^9.1.3
  image_picker: ^1.0.7
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.2
  internet_connection_checker_plus: ^2.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_theme: ^6.4.0
  keframe: 3.0.0
  logger: ^2.0.2+1
  material_design_icons_flutter: 7.0.7296
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  permission_handler_web: 0.0.2
  pretty_dio_logger: 1.3.1
  reactive_forms: ^16.1.1
  rounded_loading_button:
    git:
      url: https://github.com/scopendo/flutter_rounded_loading_button.git
      ref: master
  sentry_dart_plugin: ^1.6.0
  sentry_dio: ^7.15.0
  sentry_flutter: ^7.15.0
  shimmer: 3.0.0
  slang: ^3.29.0
  spring_button: 2.0.0
  statsfl: 2.3.0
  styled_text: ^8.1.0
  universal_platform: 1.0.0+1
  url_launcher: ^6.2.4
  url_strategy: 0.2.0
  web_socket_channel: 2.4.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  golden_toolkit: 0.15.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  mocktail_image_network: ^1.1.0
  r_flutter: ^0.9.0
  slang_build_runner: ^3.29.0
  slang_flutter: ^3.29.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/images/
    - assets/configs/
    - assets/themes/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300

# Native splash screen settings.
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash/splash_logo_light.png
  color_dark: "#000000"
  image_dark: assets/images/splash/splash_logo_dark.png
  android_12:
    image: assets/images/splash/splash_logo_light.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/splash/splash_logo_dark.png
    icon_background_color_dark: "#000000"
  fullscreen: true
