name: deps
description: The dependencies of flutter advanced boilerplate.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  back_button_interceptor: ^7.0.0
  design:
    path: ../design
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  envied: ^0.5.2
  feature_core:
    path: ../features/_core
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  hydrated_bloc: ^9.1.3
  infinite_scroll_pagination: ^4.0.0
  infrastructure:
    path: ../infrastructure
  injectable: ^2.3.2
  internet_connection_checker_plus: ^2.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_theme: ^6.4.0
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  reactive_forms: ^16.1.1
  reactive_forms_annotations: ^4.3.0
  rxdart: ^0.27.7
  sentry_flutter: ^7.14.0
  slang: ^3.28.0
  slang_flutter: ^3.28.0
  smooth_sheets: ^0.1.0
  styled_text: ^8.1.0
  super_cupertino_navigation_bar: ^2.0.5
  talker_bloc_logger: ^2.4.0
  talker_dio_logger: ^2.4.0
  talker_flutter: ^3.6.0
  uicons: ^1.0.1
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
