name: app
description: The main app of flutter advanced boilerplate.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  deps:
    path: ../deps
  flutter:
    sdk: flutter

dev_dependencies:
  pyramid_lint: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - ../design/assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: ../design/assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: ../design/assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: ../design/assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: ../design/assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
    - family: VisueltPro
      fonts:
        - asset: ../design/assets/fonts/VisueltPro/VisueltPro-Black.ttf
          weight: 900
        - asset: ../design/assets/fonts/VisueltPro/VisueltPro-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: ../design/assets/fonts/VisueltPro/VisueltPro-Bold.ttf
          weight: 700
        - asset: ../design/assets/fonts/VisueltPro/VisueltPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: ../design/assets/fonts/VisueltPro/VisueltPro-Medium.ttf
          weight: 500
        - asset: ../design/assets/fonts/VisueltPro/VisueltPro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: ../design/assets/fonts/VisueltPro/VisueltPro-Regular.ttf
          weight: 400
        - asset: ../design/assets/fonts/VisueltPro/VisueltPro-Light.ttf
          weight: 300
        - asset: ../design/assets/fonts/VisueltPro/VisueltPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: ../design/assets/fonts/VisueltPro/VisueltPro-ExtraLight.ttf
          weight: 200
        - asset: ../design/assets/fonts/VisueltPro/VisueltPro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: ../design/assets/fonts/VisueltPro/VisueltPro-Thin.ttf
          weight: 100
        - asset: ../design/assets/fonts/VisueltPro/VisueltPro-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: ../design/assets/fonts/VisueltPro/VisueltPro-Italic.ttf
          style: italic